{% set version = "0.13.0" %}

package:
  name: jupyterlab
  version: {{ version }}

source:
    fn: jupyterlab-{{ version }}.tar.gz
    url: https://pypi.io/packages/source/j/jupyterlab/jupyterlab-{{ version }}.tar.gz
    sha256: 2a94c42a533c3b72e38240db27946a0da3a86bbb98c9627a302895999695a5b1

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - notebook >=4.2

test:
  imports:
    - jupyterlab

about:
  home: https://github.com/jupyter/jupyterlab
  license: BSD 3-Clause
  summary: A pre-alpha version of a computational environment for Jupyter.

extra:
  recipe-maintainers:
    - jasongrout
    - blink1073
