{% set version = "0.26.3" %}

package:
  name: jupyterlab
  version: {{ version }}

source:
    fn: jupyterlab-{{ version }}.tar.gz
    url: https://pypi.io/packages/source/j/jupyterlab/jupyterlab-{{ version }}.tar.gz
    sha256: b53ddb022e6c39a46788330db51e627618c32264460d5b611b8b37a7fb3b142a
build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt
  entry_points:
    - jupyter-lab = jupyterlab.labapp:main
    - jupyter-labextension = jupyterlab.labextensions:main

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - jupyterlab_launcher >=0.3.0
    - notebook >=4.2

test:
  imports:
    - jupyterlab

about:
  home: https://github.com/jupyterlab/jupyterlab
  license: BSD 3-Clause
  summary: A pre-alpha version of a computational environment for Jupyter.

extra:
  recipe-maintainers:
    - jasongrout
    - blink1073
