{% set version = "0.28.3" %}

package:
  name: jupyterlab
  version: {{ version }}

source:
    fn: jupyterlab-{{ version }}.tar.gz
    url: https://pypi.io/packages/source/j/jupyterlab/jupyterlab-{{ version }}.tar.gz
    sha256: a6e34ff7a55ea41249a62668c6fcbe0c11a6d1067948382b1b07b163438b4051
build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt
  entry_points:
    - jupyter-lab = jupyterlab.labapp:main
    - jupyter-labextension = jupyterlab.labextensions:main

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - jupyterlab_launcher >=0.5.4
    - notebook >=4.3

test:
  imports:
    - jupyterlab

about:
  home: https://github.com/jupyterlab/jupyterlab
  license: BSD 3-Clause
  license_file: LICENSE
  summary: A pre-alpha version of a computational environment for Jupyter.

extra:
  recipe-maintainers:
    - jasongrout
    - blink1073
