{% set version = "0.32.0" %}
{% set sha256 = "489c6ba7df0bb8946bc47c19587e6ed35df82e3df7da0f6e8b17061c30a816e1" %}


package:
  name: jupyterlab
  version: {{ version }}

source:
    fn: jupyterlab-{{ version }}.tar.gz
    url: https://pypi.io/packages/source/j/jupyterlab/jupyterlab-{{ version }}.tar.gz
    sha256: {{ sha256 }}
build:
  number: 0
  script: python -m pip install --no-deps --ignore-installed .
  entry_points:
    - jupyter-lab = jupyterlab.labapp:main
    - jupyter-labextension = jupyterlab.labextensions:main
    - jupyter-labhub = jupyterlab.labhubapp:main

requirements:
  build:
    - python
    - pip
  run:
    - python
    - jupyterlab_launcher >=0.10.0,<0.11.0
    - notebook >=4.3
    - futures  # [py27]
    - subprocess32   # [py2k and unix]
test:
  imports:
    - jupyterlab

about:
  home: https://github.com/jupyterlab/jupyterlab
  license: BSD 3-Clause
  license_file: LICENSE
  summary: A pre-alpha version of a computational environment for Jupyter.

extra:
  recipe-maintainers:
    - jasongrout
    - blink1073
    - jochym
    - ian-r-rose
    - afshin
    - ellisonbg
