{% set version = "0.5.0" %}

package:
  name: jupyterlab
  version: {{ version }}

source:
    fn: jupyterlab-{{ version }}.tar.gz
    url: https://pypi.io/packages/source/j/jupyterlab/jupyterlab-{{ version }}.tar.gz
    sha256: ea4c83c9c76a01e3eb8568786eec89e4a21b016bb2a8b9c7e3448ed4f72140b9

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - notebook >=4.2

test:
  imports:
    - jupyterlab

about:
  home: https://github.com/jupyter/jupyterlab
  license: BSD 3-Clause
  summary: A pre-alpha version of a computational environment for Jupyter.

extra:
  recipe-maintainers:
    - jasongrout
    - blink1073

