{% set version = "0.13.1" %}

package:
  name: jupyterlab
  version: {{ version }}

source:
    fn: jupyterlab-{{ version }}.tar.gz
    url: https://pypi.io/packages/source/j/jupyterlab/jupyterlab-{{ version }}.tar.gz
    sha256: 9f93b2604874452cc3b6861e7e721505ef5a9aa57641625a886b99acbb0f6c61

build:
  number: 1
  script: python setup.py install --single-version-externally-managed --record record.txt
  entry_points:
    - jupyter-lab = jupyterlab.labapp:main
    - jupyter-labextension = jupyterlab.labextensions:main

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - notebook >=4.2

test:
  imports:
    - jupyterlab

about:
  home: https://github.com/jupyter/jupyterlab
  license: BSD 3-Clause
  summary: A pre-alpha version of a computational environment for Jupyter.

extra:
  recipe-maintainers:
    - jasongrout
    - blink1073
