{% set version = "0.27.0" %}

package:
  name: jupyterlab
  version: {{ version }}

source:
    fn: jupyterlab-{{ version }}.tar.gz
    url: https://pypi.io/packages/source/j/jupyterlab/jupyterlab-{{ version }}.tar.gz
    sha256: 22a1913f8251b7cc6b3a4a5527017b9ecf612df5f96ac1805f762894794e1344
build:
  number: 2
  script: python setup.py install --single-version-externally-managed --record record.txt
  entry_points:
    - jupyter-lab = jupyterlab.labapp:main
    - jupyter-labextension = jupyterlab.labextensions:main
  osx_is_app: True

app:
  entry: jupyter lab
  icon: icon.png
  summary: JupyterLab PRE-ALPHA
  type: desk

requirements:
  host:
    - python
    - setuptools
  run:
    - python
    - jupyterlab_launcher >=0.4.0
    - notebook >=4.3

test:
  imports:
    - jupyterlab

about:
  home: https://github.com/jupyterlab/jupyterlab
  license: BSD 3-Clause
  summary: A pre-alpha version of a computational environment for Jupyter.
  description: |
    JupyterLab is the next generation user interface for Project Jupyter. 
    It offers all the familiar building blocks of the classic Jupyter Notebook 
    (notebook, terminal, text editor, file browser, rich outputs, etc.) in a 
    flexible and powerful user inteface that can be extended through third party 
    extensions that access our public APIs. Eventually, JupyterLab will replace the 
    classic Jupyter Notebook.
  doc_url: http://jupyterlab-tutorial.readthedocs.io/en/latest/
  dev_url: https://github.com/jupyterlab/jupyterlab
  doc_source_url: https://github.com/jupyterlab/jupyterlab/tree/master/docs

extra:
  recipe-maintainers:
    - jasongrout
    - blink1073
