# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yaml and/or the recipe/meta.yaml.

language: objective-c

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=34
    - CONDA_PY=35
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "XGYLeIqgT2nPvYpmmCPoK54TbwqymDS5Xr9w4pXqd9UJ76WMY/t8pW2c0DRioQn5Rfmza7ibE+EhfUWxnZwXUIegNCiG/oj7DlB8B8yhBGHlIiKubcZuZNFpdpQqrZBzv8oB+poZ1IZOOecengW4E/U4HbyWnvwZ/u/z46VMnqocZj0rxHeVG5qveIuOgzhdvX6BBU9Ev2AO5D/RIIbKaaBLLrTFC+066hfR0shC4WnGps5ybezYyJ17/kblHVQLYgcIiFmEXH7Ja3pWPLQ7UQRdG+GLpCTJnAJGhIFSYoe2XPk0uMXmRPa6qZ/t14WjkGvPmlPpt4oStYZRJWLgD5uoJiQoX6wu+fWoCS/IB7p9G53/n/VX13jcvMAJ6mn5GNBotkrFAuvlflKrwxTB7RJOP9sYwW1jfvouE9y+nsIg+vy2hBDq/bVjvfv5VYvi63kEXtbTiVv/37yD4I2vtCkmbA0UFX0ncjJrPz0vaB58qauk69hg4wZ52JFEF3jNzSONdE3MuZQrexjMkEFXGmTzcNQihnJUVTQEVlEDo+JLQg78fad0VECp6TEd9K8vdJGx42wnVKBZswFOBxngw/a3v46UpjJhblW0rAIJXZ2YmMDEh7hrwwHRmGYwfkjuHg/XUJeTKKfwnNVK6esAJBxpSFs25fXgoxPghYAGBkc="


before_install:
    # Remove homebrew.
    - brew remove --force $(brew list)
    - brew cleanup -s
    - rm -rf $(brew --cache)

install:
    - |
      MINICONDA_URL="http://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

      export PATH=/Users/travis/miniconda3/bin:$PATH

      conda config --set show_channel_urls true
      conda update --yes conda
      conda install --yes conda-build=1.20.0 jinja2 anaconda-client
      conda config --add channels conda-forge
      

script:
  - conda build ./recipe

after_success:

  - ./ci_support/upload_or_check_non_existence.py ./recipe conda-forge --channel=main
