travis:
  secure:
    BINSTAR_TOKEN: PQl5WEZ1x8NtlPLhhYjzGCrel0ozrnTViFw1KrRQDYaMeBao62WpDgzmmcZlMBpTBPpdAIjNEXuLe6H2OBCBLF3k5YJYgSU83xDBR8ocecud/QOpdoc+n5WYEj3KIO88UURDfSY6fwZOIpix5r/UILtIdfOVSyaBeOFIlfKE7RQOF6R2gAcC7zv/TviIiiTXVSJpNKYtPXCq2WAu+gWSKf6zYI/mP5iCvK22Gc3Xif3PQVGUuoW+Rut8I2vnoKwfFCTLNtFBO6GUs/LLGMPO8FSQq9vWCzq5tix713iPRxPP6zarjpL4MgSpoNPbHUZRdRQ9G6WgXkcLm5JOtldYUSM3y2peUGvjFTSTralwDhJi8K1bugRwzqqly2b4HArEiQjmLC3h0DhohGnHcfcc2hHYHYBI96TEXuIgn/NYd0nZCdg/AC5tcawERDBhIgdnOI4gXr2ZsaC4MZ7GrEc04NjjEUjNGOjLQJuB0vYtWZj+bAemnfFvLNxJ+1GWy+TCksuDAmbVqKyDgmOyv4MEnfYwCM6xwj8krdi3J74gZKYAamjlgyNLmRL4Nfg8knc0DkCwMcpIcdXeoSEDXOucHauok0oGZq00I43znDRSQz7UKN/Gi9grMsqHUxgiFFrKmz7LtXqzUkTMNWdTcx+ttYzE7wiej8m1/KcOhG2QHpc=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
