travis:
  secure:
    BINSTAR_TOKEN: XGYLeIqgT2nPvYpmmCPoK54TbwqymDS5Xr9w4pXqd9UJ76WMY/t8pW2c0DRioQn5Rfmza7ibE+EhfUWxnZwXUIegNCiG/oj7DlB8B8yhBGHlIiKubcZuZNFpdpQqrZBzv8oB+poZ1IZOOecengW4E/U4HbyWnvwZ/u/z46VMnqocZj0rxHeVG5qveIuOgzhdvX6BBU9Ev2AO5D/RIIbKaaBLLrTFC+066hfR0shC4WnGps5ybezYyJ17/kblHVQLYgcIiFmEXH7Ja3pWPLQ7UQRdG+GLpCTJnAJGhIFSYoe2XPk0uMXmRPa6qZ/t14WjkGvPmlPpt4oStYZRJWLgD5uoJiQoX6wu+fWoCS/IB7p9G53/n/VX13jcvMAJ6mn5GNBotkrFAuvlflKrwxTB7RJOP9sYwW1jfvouE9y+nsIg+vy2hBDq/bVjvfv5VYvi63kEXtbTiVv/37yD4I2vtCkmbA0UFX0ncjJrPz0vaB58qauk69hg4wZ52JFEF3jNzSONdE3MuZQrexjMkEFXGmTzcNQihnJUVTQEVlEDo+JLQg78fad0VECp6TEd9K8vdJGx42wnVKBZswFOBxngw/a3v46UpjJhblW0rAIJXZ2YmMDEh7hrwwHRmGYwfkjuHg/XUJeTKKfwnNVK6esAJBxpSFs25fXgoxPghYAGBkc=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
