travis:
  secure:
    BINSTAR_TOKEN: AivKzRXFHmgD0ynpVgjfJWNWT3XCPszWqc5HimdgbpuOrlL6WQM3ij58uVvFS/hV1xQhQViI3cd3tRHdBaqYKnCGHrol6JM6QA6ykdpFuV4paaYYpUJFx31tAM2dzZYaNAOUOcpqtisINVwsvZDSSuQktOLEh7MxT8ki+VSRhOBgHK6wbs3ZQe0xeGTQTyKjMuaAlOqvS788Q9bUJAfp40CkVUUcpSb09EZ7GLwaV2ASND5OSTYN3x1RfeMaDcZJO8wHB0DF0/J2Hf/YVTKM9B0PZPfHVLjlCcV8pM+0DoOoiALY2yOJciCCu+tL+yEZdoTk9c2vrtmYe7HyKaIdz5XsS5U8HPqt+C4XKgVtY7rMIenSFnRTa1wAYEK8WHOyU9psT0EJWm4PeILBj0fwVGJZgHGOZEMVBFgev/7rQwpFO+ftHUtyxKhdVXlB1d6115QNVWmP1Y35emYjrqh6BKK8mxPoddSa3ueUANal/4F6Qzi7krqZ82TFJkut549Ki2xMTXY2CKF37jyy7KP7zskbZy36EGwGeNzkNHnX3CXwA8jVee7ztPULYQxpxWtRhL6tNuWS7Pu03WWAbCg+LdDNxemCZ5vLoBEZn0KS6WJ2ItJX4j2KuF1au+wLIaDbwm3NyJGi22QPaSv2BUR7hIhpSNfuTT+c3gYHnHI8e7E=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
