travis:
  secure:
    BINSTAR_TOKEN: cQEZnNXDK9cCJyosg3PVUppGUSyL8kNJs+HVPGLz4bnSC7fJ7tGFq/jLbj8t2RCxWQf+XZv8jksaj47UEpCqcyOqekF/xy9XQF7ehFk5IPgt7Y8KHeqpv0JHlf5vZGV73tpk/68rQdEvl9QTU8zcWkdmwI701QqDTvYtgxl4m03twGyuN4+Dhbz38BLmbZSLgpjB4NTVNTUPu+QpYM7cS78dYJuFWPc68pmCYAfKC6BnfMcE49y32dDtn8DP5fGzoyUY9DkJV43UbQ5HsIMuR+v+s3iuItw4u8EDU6K2I7HnYmhZvrclD+X4NLkYUoUejah8dtpBb56HE7StpEPL4EE2aotidbKWAZ9f+JOmZ2yENXV0pVQYVkuGz3JmebuyZV7W8Q/qmKdORBySNgeyhzqj6fXQJC3jXrJY+CqEYR9m7nPCLcP8VCmIA38iwE9qTxxCBG0pd9mdkpuOj9xrH4un8rozkLn7USLJX8R2+B1wPfkaoWd2UgMFpSdgbK8SbBB9UyFNUopLEhQp3oNYXXiCKxVG2+eF+Ocxsq1BXFOHvYUD8C8PgseVXuiX6dEMD+bCYtUGexmZdK8DcOHBQDyBH2Ky8agaURyGOWRogchZLeX1dtsvQnn2HrAI/byTQqUa08ng1pYCYcLGpthPvi10rf3sOVpDEtXSrKlUlkU=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
