travis:
  secure:
    BINSTAR_TOKEN: XR4bb717zmQOKFjoVVuafvVElZVxJ0G+ILbEcJ6tRofzjCxrSZ3ysO2yJ5etoItqJ9aeir8lRY+WVrxbar5qV9o5ngTP4ENF8P32Km5MICtjaT0madvgiQ8owVARpxFW0NDHOAqQ6NEGwHQv/kOpxgJE0v+JsQvvvRAcmVfJljF6WTaZLP3kKXHBE+lUp+0JEwv6zxnGKkDuF3OBWNn+zBjKW34gOGZEUlQZ18jt5TKgzi2+PfXhqQiQEBbUMM+jp27KNolROqI1XnvJmhqKLs6dwsIlfsX7ZbgMq10Q2G7D92evjK5ejJJt9xE5wZDdeJQkXtFj1+CvewCjAD6svm4AXyCddWH+BjDNsNg3m844F80zbz75Nnxhh+hVz+k4o4yjrhFQAZedsyCAY1sfy0jx4faAt+lOcibv4f8XlA11TJgloRp0lMZ7b48CALUX+Ue3b2Woqm5yyagaxwS5USMHbH6iyrHTigev6MKytOUCGEGAuUqANrqzB9jK/ySLmCnzOA3Xkg62+yGCbNNF3UJwahPN+X6yOxdPKHaXVZFiOsb7hZ4oAvEKLH4BR29wiVJVP0Uxl3/UD+1yEt/Wo5ZygiEazmfEEpUAZhdIJKNFUWnHxTPw+B90Wvv2iplMySkN5okdz6c2x+CEVeD4HF+KaBfd3B8f6Yc3SGl/Jc8=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
